language: cpp
dist: xenial
cache:
  ccache: true
  directories:
  - /home/travis/_install
os: linux

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test
    sources: &clang7_sources
      - llvm-toolchain-xenial-7
    sources: &clang8_sources
      - llvm-toolchain-xenial-8
    packages: &base_packages
    - cmake
    - cmake-data
    - lcov

env:
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install

branches:
  only:
  - master

matrix:
  fast_finish: true
  include:
    - compiler: clang
      env: CLANG_VERSION=7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
            - *clang7_sources
          packages:
            - *base_packages
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
    - compiler: clang
      env: CLANG_VERSION=7 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang7_sources
          packages:
            - *base_packages
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
    - compiler: clang
      env: CLANG_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
            - *clang8_sources
          packages:
            - *base_packages
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
    - compiler: clang
      env: CLANG_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang8_sources
          packages:
            - *base_packages
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-8
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-8


before_install:
- "env"
- "mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}"

script:
  - ./bin/build-$TRAVIS_OS_NAME.sh

after_failure:
- cat ${BUILD_PREFIX}/SeQuant/CMakeFiles/CMakeOutput.log
- cat ${BUILD_PREFIX}/SeQuant/CMakeFiles/CMakeError.log

# codecov
after_success:
  # create report
  - cd ${TRAVIS_BUILD_DIR}
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 8 ]; then lcov --gcov-tool gcov-${GCC_VERSION} --directory ${BUILD_PREFIX}/SeQuant2 --capture --output-file coverage.info; fi; # capture coverage info
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 8 ]; then lcov --remove coverage.info '/usr/*' '*/range-v3/*' '*/boost/*' '*/tests/*' '*/examples/*' '*/external/*' --output-file coverage.info; fi; # filter out non-project files
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 8 ]; then lcov --list coverage.info; fi; #debug info
  # upload report to CodeCov
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 8 ]; then bash <(curl -s https://codecov.io/bash) -t c0d0a777-cce2-48fa-8ec0-863ce1dcf446; fi;

notifications:
  slack:
    secure: pop2Eg7yMO5Uxxl8ZJ+HkPeeKKHXz9HfasDmuYFD30SOHcWetZPBxkkcNfheOrUZ9MOzebHXDz8eBEGPOrquaxv7Cr+ryFK0zqJxB4qrRXqMzdS+ppVmMULaoBNNNYq2Z/0jmrUHvZ6ZCaW7mt1R/leceZ9B0XCnUkAMcEYeQvxLpU3RQGqj8Y7N5+4DNBznEYyvlcn9CIooEkFsmdH8KLYL1SXB+RpwRwr2xO+YPJtukxS4Rd+aoEgAVnNPur/X699HGFrsnaCSQsh5rKMc1XfHT5S2T41BQG9FmyKonH0YLsPzXQMoDrHtunUHBP4FmZyBwQmtpbdPYzHvJJdhdW+09nx/O9g9VS6VZo/0U2OT/I+BCPzop+VjpsqhkmIY7UwRfvTQtuJiKdC0FKDEcuuSWDjM4wCvx9ZRq5F2wD2NuCFJ9gD+As10MqoHSp8PoAUX/iFSHLVoxnzGLF479zfbA/47+ruWJuKpw53G290XqDM7OWsgAUmwQ3+F0Hxf7CHjJ6kF9uC+6czzMkTc9NxaesjVsHmDsRwegn/yo3dnWzKer7MpjYfOJexj3KNjYTA7nF903keLyba2w6kx3W8S41XDfd98PMLDNZcN63YDFNawgqcsrSoHi/en0jsFat+8NT8K+h6elV7Js4rgqPCQbOUntID3FNh6/qp4gUQ=
